# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-11 14:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnic_number', models.CharField(max_length=20, verbose_name='CNIC Number')),
                ('university', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30, verbose_name='Your current Location (City)')),
                ('address', models.CharField(max_length=255, verbose_name='Permanent Address')),
                ('contact_number', models.CharField(max_length=30, verbose_name='Contact Number(s)')),
                ('graduation_date', models.CharField(max_length=20, verbose_name='Expected Graduation Date')),
                ('cgpa', models.CharField(max_length=10, verbose_name='CGPA')),
                ('position', models.CharField(max_length=20, verbose_name='Position in class')),
                ('interested_in_python', models.BooleanField(default=False, verbose_name='Interested in Python/Django')),
                ('interested_in_scrappy', models.BooleanField(default=False, verbose_name='Interested in Scrappy')),
                ('interested_in_andriod', models.BooleanField(default=False, verbose_name='Interested in Android')),
                ('interested_in_ios', models.BooleanField(default=False, verbose_name='Interested in iOS')),
                ('interested_in_php', models.BooleanField(default=False, verbose_name='Interested in PHP')),
                ('interested_in_javascript', models.BooleanField(default=False, verbose_name='Interested in Javascript/ReactJS')),
                ('interested_in_machine_learning', models.BooleanField(default=False, verbose_name='Interested in Machine Learning')),
                ('other_technologies', models.CharField(max_length=255, verbose_name='Any other technologies your are interested in?')),
                ('university_projects', models.TextField(verbose_name='Tell us something about your university project(s)')),
                ('extra_activities', models.TextField(verbose_name="List down any extra curricular activities you're involved in(if any)?")),
                ('freelance_work', models.TextField(verbose_name='Mention any freelance work you do/have done?')),
                ('biggest_accomplishment', models.TextField(verbose_name='Your biggest accomplishment to-date?')),
                ('makes_me_different', models.TextField(verbose_name='What makes you different from your batch mates?')),
                ('ideal_organization', models.TextField(verbose_name='Describe your ideal organization?')),
                ('why_arbisoft', models.TextField(verbose_name='Why Arbisoft?')),
                ('expected_salary', models.CharField(max_length=255, verbose_name='Your salary expectations?')),
                ('career_plans', models.TextField(verbose_name='Your career plans two years down the line?')),
                ('references', models.TextField(verbose_name='Mention two university references along with their position and contact number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
