# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-15 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshgrad_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinfo',
            name='other_technologies',
            field=models.TextField(verbose_name='Which technologies are you interested to work in? (Python/Django, Scrapy, Android, iOS, PHP, Javascript/ReactJS, Machine Learning)'),
        ),
    ]
