# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2022-02-23 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshgrad_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='CandidateInfo',
        ),
    ]
