# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2022-02-23 21:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freshgrad_test', '0002_auto_20220223_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm_password', models.CharField(blank=True, max_length=50)),
                ('cnic_number', models.CharField(max_length=20, verbose_name='CNIC Number')),
                ('age', models.CharField(max_length=2, verbose_name='Age (between 18 to 30)')),
                ('university', models.CharField(choices=[(b'COMSATS', 'COMSATS'), (b'University of Engineering & Technology', 'University of Engineering & Technology'), (b'National University of Sciences & Technology', 'National University of Sciences & Technology'), (b'Bahria University', 'Bahria University'), (b'NAMAL', 'NAMAL'), (b'University of Gujrat', 'University of Gujrat'), (b'Islamia University of Bahawalpur', 'Islamia University of Bahawalpur'), (b'PUCIT', 'PUCIT'), (b'GIKI', 'GIKI'), (b'FAST', 'FAST'), (b'Superior University', 'Superior University'), (b'Imperial College', 'Imperial College'), (b'University of Central Punjab', 'University of Central Punjab'), (b'Forman Christian College', 'Forman Christian College'), (b'Szabist', 'Szabist'), (b'Lahore College for Women', 'Lahore College for Women'), (b'University of Lahore', 'University of Lahore'), (b'Kinnaird College', 'Kinnaird College'), (b'University of Management & Technology', 'University of Management & Technology'), (b'AJK University', 'AJK University'), (b'BZU Multan', 'BZU Multan'), (b'Islamia College University', 'Islamia College University'), (b'AIR University', 'AIR University'), (b'Information Technology University', 'Information Technology University'), (b'University of Peshawar', 'University of Peshawar'), (b'Virtual University', 'Virtual University'), (b'Lahore University of Management & Sciences', 'Lahore University of Management & Sciences'), (b'University of Sargodha', 'University of Sargodha'), (b'International Islamic University', 'International Islamic University'), (b'Other', 'Other')], max_length=100)),
                ('campus', models.CharField(choices=[(b'Lahore', b'Lahore'), (b'Faisalabad', b'Faisalabad'), (b'Islamabad', b'Islamabad'), (b'Peshawar', b'Peshawar'), (b'Taxilla', b'Taxilla'), (b'Vehari', b'Vehari'), (b'Gujrat', b'Gujrat'), (b'Mianwali', b'Mianwali'), (b'Multan', b'Multan'), (b'Bahawalpur', b'Bahawalpur'), (b'Bahawalnagar', b'Bahawalnagar'), (b'Rahim Yar Khan', b'Rahim Yar Khan'), (b'Sargodha', b'Sargodha'), (b'Other', b'Other')], max_length=30)),
                ('other_university', models.CharField(blank=True, max_length=50, verbose_name='University details, if not in list')),
                ('city', models.CharField(max_length=30, verbose_name='Your current Location (City)')),
                ('address', models.CharField(max_length=255, verbose_name='Permanent Address')),
                ('contact_number', models.CharField(max_length=30, verbose_name='Contact Number(s)')),
                ('graduation_date', models.CharField(max_length=20, verbose_name='Expected Graduation Date')),
                ('cgpa', models.CharField(max_length=10, verbose_name='CGPA')),
                ('position', models.CharField(max_length=20, verbose_name='Position in class')),
                ('interested_in_python', models.BooleanField(default=False, verbose_name='Interested in Python/Django')),
                ('interested_in_scrappy', models.BooleanField(default=False, verbose_name='Interested in Scrappy')),
                ('interested_in_andriod', models.BooleanField(default=False, verbose_name='Interested in Android')),
                ('interested_in_ios', models.BooleanField(default=False, verbose_name='Interested in iOS')),
                ('interested_in_php', models.BooleanField(default=False, verbose_name='Interested in PHP')),
                ('interested_in_javascript', models.BooleanField(default=False, verbose_name='Interested in Javascript/ReactJS')),
                ('interested_in_machine_learning', models.BooleanField(default=False, verbose_name='Interested in Machine Learning')),
                ('makes_me_different', models.CharField(max_length=20, verbose_name='What makes you different from your batch mates?')),
                ('ideal_organization', models.CharField(max_length=100, verbose_name='Describe your ideal organization? (100 characters at max)')),
                ('why_arbisoft', models.TextField(max_length=51, verbose_name='Why Arbisoft? (50 characters at max)')),
                ('expected_salary', models.TextField(verbose_name='Your salary expections?')),
                ('career_plans', models.TextField(blank=True, max_length=100, verbose_name='Your career plans two years down the line? (100 characters at max)')),
                ('references', models.TextField(blank=True, verbose_name='Mention two university references along with their position and contact number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
