# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-20 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshgrad_test', '0002_auto_20190115_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinfo',
            name='expected_salary',
            field=models.TextField(verbose_name='Your salary expectations?'),
        ),
    ]
