# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-31 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshgrad_test', '0005_auto_20191023_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinfo',
            name='campus',
            field=models.CharField(choices=[(b'Lahore', b'Lahore'), (b'Faisalabad', b'Faisalabad'), (b'Islamabad', b'Islamabad'), (b'Peshawar', b'Peshawar'), (b'Taxilla', b'Taxilla'), (b'Vehari', b'Vehari'), (b'Gujrat', b'Gujrat'), (b'Mianwali', b'Mianwali'), (b'Multan', b'Multan'), (b'Bahawalpur', b'Bahawalpur'), (b'Bahawalnagar', b'Bahawalnagar'), (b'Rahim Yar Khan', b'Rahim Yar Khan'), (b'Sargodha', b'Sargodha'), (b'Other', b'Other')], max_length=31),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='ideal_organization',
            field=models.TextField(blank=True, verbose_name='Describe your ideal organization?'),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='other_university',
            field=models.CharField(max_length=50, verbose_name='University details, if not in list (optional)'),
        ),
    ]
