# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-31 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshgrad_test', '0007_auto_20200131_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinfo',
            name='other_university',
            field=models.CharField(max_length=50, verbose_name='University details, if not in list'),
        ),
    ]
