# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-31 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshgrad_test', '0008_auto_20200131_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateinfo',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='other_university',
            field=models.CharField(blank=True, max_length=50, verbose_name='University details, if not in list'),
        ),
    ]
