# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-01-31 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshgrad_test', '0009_auto_20200131_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinfo',
            name='ideal_organization',
            field=models.TextField(max_length=51, verbose_name='Describe your ideal organization? (50 characters at max)'),
        ),
    ]
