# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-02-03 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshgrad_test', '0012_auto_20200203_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinfo',
            name='makes_me_different',
            field=models.CharField(max_length=8, verbose_name='What makes you different from your batch mates?'),
        ),
    ]
