# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-02-10 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshgrad_test', '0014_auto_20200206_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinfo',
            name='biggest_accomplishment',
            field=models.TextField(max_length=200, verbose_name='Your biggest acomplishment to-date? (200 characters at max)'),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='career_plans',
            field=models.TextField(max_length=100, verbose_name='Your career plans two years down the line? (100 characters at max)'),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='extra_activities',
            field=models.TextField(max_length=100, verbose_name="List down any extra curricular activitiez you're involved in(if any)? (100 characters at max)"),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='freelance_work',
            field=models.TextField(max_length=200, verbose_name='Mention any freelance work you do/have done? (200 characters at max)'),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='why_arbisoft',
            field=models.TextField(max_length=50, verbose_name='Why Arbisoft? (50 characters at max)'),
        ),
    ]
