# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-02-12 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshgrad_test', '0015_auto_20200210_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinfo',
            name='makes_me_different',
            field=models.CharField(max_length=20, verbose_name='What makes you different from your batch mates?'),
        ),
    ]
