# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-02-12 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshgrad_test', '0016_auto_20200212_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateinfo',
            name='age',
            field=models.IntegerField(default=18, verbose_name='Age (between 18 to 30)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='career_plans',
            field=models.TextField(blank=True, max_length=100, verbose_name='Your career plans two years down the line? (100 characters at max)'),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='references',
            field=models.TextField(blank=True, verbose_name='Mention two university references along with their position and contact number'),
        ),
    ]
