# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-02-13 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshgrad_test', '0019_auto_20200213_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinfo',
            name='age',
            field=models.TextField(max_length=2, verbose_name='Age (between 18 to 30)'),
        ),
    ]
