# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2022-02-21 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshgrad_test', '0021_auto_20200213_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateinfo',
            name='biggest_accomplishment',
        ),
        migrations.RemoveField(
            model_name='candidateinfo',
            name='extra_activities',
        ),
        migrations.RemoveField(
            model_name='candidateinfo',
            name='freelance_work',
        ),
        migrations.RemoveField(
            model_name='candidateinfo',
            name='university_projects',
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='ideal_organization',
            field=models.CharField(max_length=50, verbose_name='Describe your ideal organization? (50 characters at max)'),
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='why_arbisoft',
            field=models.TextField(max_length=51, verbose_name='Why Arbisoft? (50 characters at max)'),
        ),
    ]
