# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2022-02-22 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshgrad_test', '0022_auto_20220221_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateinfo',
            name='expected_salary',
            field=models.TextField(verbose_name='Your salary expections?'),
        ),
    ]
