# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2022-02-22 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freshgrad_test', '0023_auto_20220221_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateinfo',
            name='other_technologies',
        ),
    ]
